In [1]:
#Ensemble  Prob Max Voting
#LogisticRegression
#naive-bayes
#HMM

In [2]:
#importing utility modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import log_loss

# importing machine learning models for prediction
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from hmmlearn import hmm

# importing voting classifier
from sklearn.ensemble import VotingClassifier


In [3]:
# loading train data set in dataframe from train_data.csv file
col_names = ['Frost_pt','Temp_MAX','Temp_MIN','Specific_Hum','Relative_Hum','Winds_Max','Winds_Min','Rain','cDay','Rain1','Rain2','Rain3','Rain4','Rain5']
feature_cols=['Frost_pt','Temp_MAX','Temp_MIN','Specific_Hum','Relative_Hum','Winds_Max','Winds_Min']

df=pd.read_csv("D:/data/tan/train.csv",header=None,names=col_names)

# getting target data from the dataframe
target = df["Rain"]

# getting train data from the dataframe
train = df[feature_cols]

#HMM
y =  df.Rain
X =  df.iloc[:, 0:7].values  
observations = np.array(X)
rain_states = np.array(y)

In [4]:
# Splitting between train data into training and validation dataset
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.20)

In [5]:
# initializing all the model objects with default parameters
model_1 = LogisticRegression(random_state=20)
model_2 = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)
model_3 = KNeighborsClassifier(n_neighbors=2)

In [6]:
# training all the model on the training dataset
model_1.fit(X_train, y_train) # LR
model_2.fit(X_train, y_train) # DT
model_3.fit(X_train, y_train) # KNN

KNeighborsClassifier(n_neighbors=2)

In [7]:
# predicting the output on the validation dataset
pred_1 = model_1.predict(X_test)
pred_2 = model_2.predict(X_test)
pred_3 = model_3.predict(X_test)

In [8]:
# Making the final model using voting classifier
final_model = VotingClassifier(estimators=[('lr', model_1), ('xgb', model_2), ('rf', model_3)], voting='hard')


In [9]:
# training all the model on the train dataset
final_model.fit(X_train, y_train)

VotingClassifier(estimators=[('lr', LogisticRegression(random_state=20)),
                             ('xgb',
                              DecisionTreeClassifier(max_depth=3,
                                                     min_samples_leaf=5,
                                                     random_state=100)),
                             ('rf', KNeighborsClassifier(n_neighbors=2))])

In [10]:
# predicting the output on the test dataset
pred_final = final_model.predict(X_test)

In [11]:
# printing log loss between actual and predicted value

print(log_loss(y_test, pred_final))

5.383943664736997


In [12]:
#pred_final

In [13]:
# printing the mean squared error between real value and predicted value
print(mean_squared_error(y_test, pred_1))
print(mean_squared_error(y_test, pred_2))
print(mean_squared_error(y_test, pred_3))
print(mean_squared_error(y_test, pred_final))

0.15393386545039908
0.18244013683010263
0.18015963511972635
0.14937286202964653


In [14]:
print("LogisticRegression")
print(confusion_matrix(y_test, pred_1))

LogisticRegression
[[501  64]
 [ 71 241]]


In [15]:
print("DecisionTreeClassifier")
print(confusion_matrix(y_test, pred_2))

DecisionTreeClassifier
[[544  21]
 [139 173]]


In [16]:
print("KNeighborsClassifier")
print(confusion_matrix(y_test, pred_3))

KNeighborsClassifier
[[532  33]
 [125 187]]


In [17]:
print("Ensemble -Max Voting Method")
print(confusion_matrix(y_test, pred_final))

Ensemble -Averaging Method
[[542  23]
 [108 204]]
