In [1]:
# Ensembled Average Method
#LogisticRegression
#naive-bayes
#HMM


In [2]:
#importing utility modules
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import classification_report, confusion_matrix

# importing machine learning models for prediction
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from hmmlearn import hmm


In [3]:
# loading train data set in dataframe from train_data.csv file
col_names = ['Frost_pt','Temp_MAX','Temp_MIN','Specific_Hum','Relative_Hum','Winds_Max','Winds_Min','Rain','cDay','Rain1','Rain2','Rain3','Rain4','Rain5']
feature_cols=['Frost_pt','Temp_MAX','Temp_MIN','Specific_Hum','Relative_Hum','Winds_Max','Winds_Min']

df=pd.read_csv("D:/data/tan/train.csv",header=None,names=col_names)

# getting target data from the dataframe
target = df["Rain"]

# getting train data from the dataframe
train = df[feature_cols]

y =  df.Rain
X =  df.iloc[:, 0:7].values  
observations = np.array(X)
rain_states = np.array(y)

In [4]:
#HMM
X_trainH, X_testH, y_trainH, y_testH = train_test_split(observations, rain_states, test_size=0.20, random_state=149)

In [5]:
# Splitting between train data into training and validation dataset
X_train, X_test, y_train, y_test = train_test_split(train, target, test_size=0.20)

In [6]:
# initializing all the model objects with default parameters
model_1 = LogisticRegression()
model_2 = model = GaussianNB() #DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)
model_3 = hmm.GaussianHMM(n_components=2) #KNeighborsClassifier(n_neighbors=2)

In [7]:
# training all the model on the training dataset
model_1.fit(X_train, y_train) # LR
model_2.fit(X_train, y_train) # naive-bayes
model_3.fit(X_trainH) # HMM

C:\Users\Ravindra\anaconda3\envs\tensorflow\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


GaussianHMM(n_components=2)

In [8]:
# predicting the output on the validation dataset
pred_1 = model_1.predict(X_test)
pred_2 = model_2.predict(X_test)
pred_3 = model_3.predict(X_test)

In [9]:
# final prediction after averaging on the prediction of all 3 models
pred_final = (pred_1+pred_2+pred_3)/3.0

In [10]:
pred_final1=pred_final>0.5
#pred_final1

In [11]:
# printing the mean squared error between real value and predicted value
print(mean_squared_error(y_test, pred_1))
print(mean_squared_error(y_test, pred_2))
print(mean_squared_error(y_test, pred_3))
print(mean_squared_error(y_test, pred_final))

0.1630558722919042
0.19840364880273662
0.19270239452679588
0.1565944507791714


In [12]:
print("LogisticRegression")
print(confusion_matrix(y_test, pred_1))

LogisticRegression
[[487  62]
 [ 81 247]]


In [13]:
print("naive-bayes")
print(confusion_matrix(y_test, pred_2))

naive-bayes
[[462  87]
 [ 87 241]]


In [14]:
print("HMM")
print(confusion_matrix(y_test, pred_3))

HMM
[[500  49]
 [120 208]]


In [15]:
print("Ensemble Prob-Averaging Method")
print(confusion_matrix(y_test, pred_final1))

Ensemble Prob-Averaging Method
[[489  60]
 [ 99 229]]
